### ISSUE TITLE
Missing nexpect version 1.0.237 on nuget.org

### ISSUE THREAD

**Issue by viceice** [fluffynuts/NExpect#25]
`NExpect.Matchers.NSubstitute` v1.0.237 depends on `NExpect` v1.0.237 which is missing on nuget.org.

**Comment by fluffynuts** [comment]
Hi @viceice 

Thanks for reporting! There was an issue with my automated releases such that some packages weren't being properly pushed. Please try the latest release (:

Also, apologies for the delayed response - I missed the notification of this issue ):
