### ISSUE TITLE
To.Contain.Only(n).Matched.By(...) ignores By-filter

### ISSUE THREAD

**Issue by UrsMetz** [fluffynuts/NExpect#29]
Since version 1.0.268 the following test is failing:
```csharp
[Test]
public void Test1()
{
    Expect(new List<int> { 1, 2 }).To.Contain.Only(1).Matched.By(i => i % 2 == 0);
}
```
I think this is because in commit 73b057f changed the matcher logic (and dropped the `.Where(...)` clause), cf. https://github.com/fluffynuts/NExpect/blob/29bdeb533cfa68975d6c419188fe0aa881da41ab/src/NExpect/CollectionMatchers.cs#L472 and following.

**Comment by fluffynuts** [comment]
Yes, the prior behavior was a _bug_ (hence the commit comment for 73b057f) 😞 

- `Only` restricts the _total_ number of items in the collection
- `Exactly` matches the number provided against the matcher function

So the test above should _never_ have passed. This was corrected. To achieve the result you're looking for, you should do:

```csharp
Expect(new [] { 1, 2,})
	.To.Contain.Exactly(1)
	.Matched.By(i => I % 2 == 0);
```

This keeps the functionality in line with other usages of `Only`. For instance:
```csharp
Expect(new[] { 1 })
	.To.Contain.Only(1).Item(); // passes
Expect(new[] { 1, 2, })
	.To.Contain.Only(1).Item(); // fails
```

I'm really sorry for the bug - and I had knock-on tests that I had to fix from co-workers who had also used `Only` this way before too ):

`Only` essentially performs a two-for-one test with `.Matched.By`:
1. tests that the collection size (total) is met
2. tests that the items in the collection _all_ match the given matcher function

ie, it performs the same as:
```csharp
var collection = new[] { 2 };
Expect(collection)
	.To.Contain.Only(1).Item();
Expect(collection)
	.To.Contain.Exactly(1)
	.Matched.By(i => i % 2 == 0);
// or
Expect(collection)
	.To.Contain.All
	.Matched.By(i => i % 2 == 0);
```

**Comment by UrsMetz** [comment]
I see, thanks for the thorough explanation.
